safety_bonds:
    landing_detector:
        priority: 40
    fc_comms_msp:
        priority: 50
    fc_comms_crazyflie:
        priority: 50
    long_range_altimeter:
        priority: 60
    orientation_filter:
        priority: 100
    velocity_filter:
        priority: 150
    low_level_motion:
        priority: 200
    motion_command_coordinator:
        priority: 250
    takeoff_land_abstract:
        priority: 1000
    motors_test:
        priority: 1000
    takeoff_translate_land_abstract:
        priority: 1000
    track_roomba_abstract:
        priority: 1000
    hold_position_abstract:
        priority: 1000
    hit_roomba_abstract:
        priority: 1000
    velocity_test_abstract:
        priority: 1000
    block_roomba_abstract: 
        priority: 1000
    roomba_request_executer_test_abstract:
        priority: 1000
    invalid_task_transition_test:
        priority: 1000
    competition_demo_abstract:
        priority: 1000
