<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="greased_lightning">
    <link name="quad" />
    <link name="center_of_lift" />
    <link name="lidarlite" />
    <link name="short_distance_lidar" />
    <link name="base_footprint" />
    <link name="foot1" />
    <link name="foot2" />
    <link name="foot3" />
    <link name="foot4" />
    <link name="bottom_camera_link" />
    <link name="bottom_camera_rgb_optical_frame" />
    <link name="front_camera_link" />
    <link name="left_camera_link" />
    <link name="right_camera_link" />
    <link name="back_camera_link" />

    <joint name="quad_to_center_of_lift" type="fixed">
        <parent link="quad" />
        <child link="center_of_lift" />
        <origin xyz="0 0 0.06" />
    </joint>

    <joint name="quad_to_lidarlite" type="fixed">
        <parent link="quad" />
        <child link="lidarlite" />
        <origin xyz="-0.163 0.163 0.02" rpy="0 ${pi/2} 0" />
    </joint>

    <joint name="quad_to_short_distance_lidar" type="fixed">
        <parent link="quad" />
        <child link="short_distance_lidar" />
        <origin xyz="0.25 0.33 -0.043" rpy="0 ${pi/2} 0" />
    </joint>

    <joint name="quad_to_base_footprint" type="fixed">
        <parent link="quad" />
        <child link="base_footprint" />
        <origin xyz="0 0 -0.215" />
    </joint>

    <xacro:property name="foot_dist" value="0.233" />
    <xacro:macro name="foot" params="name reflect_x reflect_y">
        <joint name="base_footprint_to_${name}" type="fixed">
            <parent link="base_footprint" />
            <child link="${name}" />
            <origin xyz="${foot_dist*reflect_x} ${foot_dist*reflect_y} 0" />
        </joint>
    </xacro:macro>

    <xacro:foot name="foot1" reflect_x="1" reflect_y="1" />
    <xacro:foot name="foot2" reflect_x="-1" reflect_y="1" />
    <xacro:foot name="foot3" reflect_x="-1" reflect_y="-1" />
    <xacro:foot name="foot4" reflect_x="1" reflect_y="-1" />

    <joint name="quad_to_bottom_camera_link" type="fixed">
        <parent link="quad" />
        <child link="bottom_camera_link" />
        <origin xyz="0 0.07 -0.09" rpy="0 ${pi/2} -${pi/2}" />
    </joint>

    <joint name="bottom_camera_link_to_bottom_camera_rgb_optical_frame"
        type="fixed">
        <parent link="bottom_camera_link" />
        <child link="bottom_camera_rgb_optical_frame" />
        <origin rpy="-${pi/2} 0 -${pi/2}" />
    </joint>

    <xacro:property name="camera_z" value="-0.13" />
    <xacro:property name="camera_horiz_offset" value="0.20" />
    <xacro:macro name="side_camera" params="name pitch yaw">
        <joint name="quad_to_${name}_camera_link" type="fixed">
            <parent link="quad" />
            <child link="${name}_camera_link" />
            <origin
                xyz="${camera_horiz_offset*cos(yaw)} ${camera_horiz_offset*sin(yaw)} ${camera_z}"
                rpy="0 ${pitch} ${yaw}" />
        </joint>
    </xacro:macro>

    <xacro:side_camera name="front" pitch="${20*pi/180}" yaw="${0*pi/2}" />
    <xacro:side_camera name="left"  pitch="${35*pi/180}" yaw="${1*pi/2}" />
    <xacro:side_camera name="back"  pitch="${20*pi/180}" yaw="${2*pi/2}" />
    <xacro:side_camera name="right" pitch="${35*pi/180}" yaw="${3*pi/2}" />
</robot>
